[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
phygital_payments = "EMxvE5xxqXTWwTt391NsULydeT2QyG2UdN45VHpFxeVH"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
