[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
phygital_payments = "DQJiqvPmzfsrd2UnAfG5msSvgo1X8QXvm1q4axUsdvok"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
