/**
 * AUTOGENERATED by Codama — instruction data encoders patched for program-v2 runtime layout.
 * Re-applied by scripts/patch-lazorkit-instructions.mjs after `pnpm generate:client`.
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/kit/program-client-core";
import { concatBytes, encodeU16Le, encodeU64Le } from "../../bytes";
import { LAZORKIT_PROGRAM_PROGRAM_ADDRESS } from "../programs";

export const CREATE_SESSION_DISCRIMINATOR = 5;

export function getCreateSessionDiscriminatorBytes(): ReadonlyUint8Array {
  return getU8Encoder().encode(CREATE_SESSION_DISCRIMINATOR);
}

export type CreateSessionInstruction<
  TProgram extends string = typeof LAZORKIT_PROGRAM_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountWallet extends string | AccountMeta<string> = string,
  TAccountAdminAuthority extends string | AccountMeta<string> = string,
  TAccountSession extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountRentSysvar extends string | AccountMeta<string> =
    "SysvarRent111111111111111111111111111111111",
  TAccountAuthorizerSigner extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? ReadonlySignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountWallet extends string
        ? ReadonlyAccount<TAccountWallet>
        : TAccountWallet,
      TAccountAdminAuthority extends string
        ? WritableAccount<TAccountAdminAuthority>
        : TAccountAdminAuthority,
      TAccountSession extends string
        ? WritableAccount<TAccountSession>
        : TAccountSession,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountRentSysvar extends string
        ? ReadonlyAccount<TAccountRentSysvar>
        : TAccountRentSysvar,
      TAccountAuthorizerSigner extends string
        ? ReadonlySignerAccount<TAccountAuthorizerSigner> &
            AccountSignerMeta<TAccountAuthorizerSigner>
        : TAccountAuthorizerSigner,
      ...TRemainingAccounts,
    ]
  >;

export type CreateSessionInstructionData = {
  discriminator: number;
  sessionKey: ReadonlyUint8Array;
  expiresAt: bigint;
};

export type CreateSessionInstructionDataArgs = {
  sessionKey: ReadonlyUint8Array;
  expiresAt: number | bigint;
  actions?: ReadonlyUint8Array;
};

export function getCreateSessionInstructionDataEncoder(): Encoder<CreateSessionInstructionDataArgs> {
  return {
    getSizeFromValue: (value) => {
      const actions = value.actions ?? new Uint8Array();
      return actions.length === 0 ? 41 : 43 + actions.length;
    },
    write(value, bytes, offset) {
      bytes.set(this.encode(value), offset);
    },
    encode(value) {
      if (value.sessionKey.length !== 32) {
        throw new Error("sessionKey must be 32 bytes");
      }
      const expiresAt =
        typeof value.expiresAt === "bigint" ? value.expiresAt : BigInt(value.expiresAt);
      const actions = value.actions ?? new Uint8Array();
      if (actions.length === 0) {
        return concatBytes([
          Uint8Array.of(CREATE_SESSION_DISCRIMINATOR),
          value.sessionKey,
          encodeU64Le(expiresAt),
        ]);
      }
      return concatBytes([
        Uint8Array.of(CREATE_SESSION_DISCRIMINATOR),
        value.sessionKey,
        encodeU64Le(expiresAt),
        encodeU16Le(actions.length),
        actions,
      ]);
    },
  };
}

export function getCreateSessionInstructionDataDecoder(): Decoder<CreateSessionInstructionData> {
  return {
    decode(bytes) {
      if (bytes.length < 41) {
        throw new Error("CreateSession instruction data too short");
      }
      const sessionKey = bytes.slice(1, 33);
      const expiresAt = new DataView(
        bytes.buffer,
        bytes.byteOffset + 33,
        8,
      ).getBigUint64(0, true);
      return {
        discriminator: CREATE_SESSION_DISCRIMINATOR,
        sessionKey,
        expiresAt,
      };
    },
  };
}

export function getCreateSessionInstructionDataCodec(): Codec<
  CreateSessionInstructionDataArgs,
  CreateSessionInstructionData
> {
  return combineCodec(
    getCreateSessionInstructionDataEncoder(),
    getCreateSessionInstructionDataDecoder(),
  );
}

export type CreateSessionInput<
  TAccountPayer extends string = string,
  TAccountWallet extends string = string,
  TAccountAdminAuthority extends string = string,
  TAccountSession extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountRentSysvar extends string = string,
  TAccountAuthorizerSigner extends string = string,
> = {
  /** Transaction payer and rent contributor */
  payer: TransactionSigner<TAccountPayer>;
  /** Wallet PDA */
  wallet: Address<TAccountWallet>;
  /** Admin/Owner authority PDA authorizing logic (counter incremented) */
  adminAuthority: Address<TAccountAdminAuthority>;
  /** New session PDA to be created */
  session: Address<TAccountSession>;
  /** System Program */
  systemProgram?: Address<TAccountSystemProgram>;
  /** Rent Sysvar */
  rentSysvar?: Address<TAccountRentSysvar>;
  /** Optional signer for Ed25519 authentication */
  authorizerSigner?: TransactionSigner<TAccountAuthorizerSigner>;
  sessionKey: CreateSessionInstructionDataArgs["sessionKey"];
  expiresAt: CreateSessionInstructionDataArgs["expiresAt"];
  actions?: CreateSessionInstructionDataArgs["actions"];
};

export function getCreateSessionInstruction<
  TAccountPayer extends string,
  TAccountWallet extends string,
  TAccountAdminAuthority extends string,
  TAccountSession extends string,
  TAccountSystemProgram extends string,
  TAccountRentSysvar extends string,
  TAccountAuthorizerSigner extends string,
  TProgramAddress extends Address = typeof LAZORKIT_PROGRAM_PROGRAM_ADDRESS,
>(
  input: CreateSessionInput<
    TAccountPayer,
    TAccountWallet,
    TAccountAdminAuthority,
    TAccountSession,
    TAccountSystemProgram,
    TAccountRentSysvar,
    TAccountAuthorizerSigner
  >,
  config?: { programAddress?: TProgramAddress },
): CreateSessionInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountWallet,
  TAccountAdminAuthority,
  TAccountSession,
  TAccountSystemProgram,
  TAccountRentSysvar,
  TAccountAuthorizerSigner
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? LAZORKIT_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: false },
    wallet: { value: input.wallet ?? null, isWritable: false },
    adminAuthority: { value: input.adminAuthority ?? null, isWritable: true },
    session: { value: input.session ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    rentSysvar: { value: input.rentSysvar ?? null, isWritable: false },
    authorizerSigner: {
      value: input.authorizerSigner ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.rentSysvar.value) {
    accounts.rentSysvar.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("wallet", accounts.wallet),
      getAccountMeta("adminAuthority", accounts.adminAuthority),
      getAccountMeta("session", accounts.session),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("rentSysvar", accounts.rentSysvar),
      getAccountMeta("authorizerSigner", accounts.authorizerSigner),
    ],
    data: getCreateSessionInstructionDataEncoder().encode(
      args as CreateSessionInstructionDataArgs,
    ),
    programAddress,
  } as CreateSessionInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountWallet,
    TAccountAdminAuthority,
    TAccountSession,
    TAccountSystemProgram,
    TAccountRentSysvar,
    TAccountAuthorizerSigner
  >);
}

export type ParsedCreateSessionInstruction<
  TProgram extends string = typeof LAZORKIT_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Transaction payer and rent contributor */
    payer: TAccountMetas[0];
    /** Wallet PDA */
    wallet: TAccountMetas[1];
    /** Admin/Owner authority PDA authorizing logic (counter incremented) */
    adminAuthority: TAccountMetas[2];
    /** New session PDA to be created */
    session: TAccountMetas[3];
    /** System Program */
    systemProgram: TAccountMetas[4];
    /** Rent Sysvar */
    rentSysvar: TAccountMetas[5];
    /** Optional signer for Ed25519 authentication */
    authorizerSigner?: TAccountMetas[6] | undefined;
  };
  data: CreateSessionInstructionData;
};

export function parseCreateSessionInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCreateSessionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 7,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === LAZORKIT_PROGRAM_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      wallet: getNextAccount(),
      adminAuthority: getNextAccount(),
      session: getNextAccount(),
      systemProgram: getNextAccount(),
      rentSysvar: getNextAccount(),
      authorizerSigner: getNextOptionalAccount(),
    },
    data: getCreateSessionInstructionDataDecoder().decode(instruction.data),
  };
}
