/**
 * AUTOGENERATED by Codama — instruction data encoders patched for program-v2 runtime layout.
 * Re-applied by scripts/patch-lazorkit-instructions.mjs after `pnpm generate:client`.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/kit/program-client-core";
import { concatBytes } from "../../bytes";
import { LAZORKIT_PROGRAM_PROGRAM_ADDRESS } from "../programs";

export const CREATE_WALLET_DISCRIMINATOR = 0;

export function getCreateWalletDiscriminatorBytes(): ReadonlyUint8Array {
  return getU8Encoder().encode(CREATE_WALLET_DISCRIMINATOR);
}

export type CreateWalletInstruction<
  TProgram extends string = typeof LAZORKIT_PROGRAM_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountWallet extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountRentSysvar extends string | AccountMeta<string> =
    "SysvarRent111111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountWallet extends string
        ? WritableAccount<TAccountWallet>
        : TAccountWallet,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountAuthority extends string
        ? WritableAccount<TAccountAuthority>
        : TAccountAuthority,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountRentSysvar extends string
        ? ReadonlyAccount<TAccountRentSysvar>
        : TAccountRentSysvar,
      ...TRemainingAccounts,
    ]
  >;

export type CreateWalletInstructionData = {
  discriminator: number;
  userSeed: ReadonlyUint8Array;
  authType: number;
  authBump: number;
  authPubkey: ReadonlyUint8Array;
  credentialHash: ReadonlyUint8Array;
  rpId: string;
};

export type CreateWalletInstructionDataArgs = {
  userSeed: ReadonlyUint8Array;
  authType: number;
  authPubkey: ReadonlyUint8Array;
  credentialHash: ReadonlyUint8Array;
  rpId: string;
  authBump?: number;
};

function encodeSecp256r1Tail(args: CreateWalletInstructionDataArgs): Uint8Array {
  const rpId = new TextEncoder().encode(args.rpId);
  if (rpId.length === 0 || rpId.length > 253) {
    throw new Error("Invalid rpId");
  }
  return concatBytes([
    args.credentialHash,
    args.authPubkey,
    Uint8Array.of(rpId.length),
    rpId,
  ]);
}

export function getCreateWalletInstructionDataEncoder(): Encoder<CreateWalletInstructionDataArgs> {
  return {
    getSizeFromValue: (value) =>
      1 + 40 + 32 + 33 + 1 + new TextEncoder().encode(value.rpId).length,
    write(value, bytes, offset) {
      const encoded = this.encode(value);
      bytes.set(encoded, offset);
    },
    encode(value) {
      if (value.userSeed.length !== 32) {
        throw new Error("userSeed must be 32 bytes");
      }
      if (value.authPubkey.length !== 33) {
        throw new Error("authPubkey must be 33 bytes");
      }
      if (value.credentialHash.length !== 32) {
        throw new Error("credentialHash must be 32 bytes");
      }
      const header = new Uint8Array(40);
      header.set(value.userSeed, 0);
      header[32] = value.authType;
      header[33] = value.authBump ?? 0;
      return concatBytes([
        Uint8Array.of(CREATE_WALLET_DISCRIMINATOR),
        header,
        encodeSecp256r1Tail(value),
      ]);
    },
  };
}

export function getCreateWalletInstructionDataDecoder(): Decoder<CreateWalletInstructionData> {
  return {
    decode(bytes) {
      if (bytes.length < 1 + 40 + 66) {
        throw new Error("CreateWallet instruction data too short");
      }
      const body = bytes.slice(1);
      const userSeed = body.slice(0, 32);
      const authType = body[32]!;
      const authBump = body[33]!;
      const credentialHash = body.slice(40, 72);
      const authPubkey = body.slice(72, 105);
      const rpIdLen = body[105]!;
      const rpId = new TextDecoder().decode(body.slice(106, 106 + rpIdLen));
      return {
        discriminator: CREATE_WALLET_DISCRIMINATOR,
        userSeed,
        authType,
        authBump,
        authPubkey,
        credentialHash,
        rpId,
      };
    },
  };
}

export function getCreateWalletInstructionDataCodec(): Codec<
  CreateWalletInstructionDataArgs,
  CreateWalletInstructionData
> {
  return combineCodec(
    getCreateWalletInstructionDataEncoder(),
    getCreateWalletInstructionDataDecoder(),
  );
}

export type CreateWalletInput<
  TAccountPayer extends string = string,
  TAccountWallet extends string = string,
  TAccountVault extends string = string,
  TAccountAuthority extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountRentSysvar extends string = string,
> = {
  /** Payer and rent contributor */
  payer: TransactionSigner<TAccountPayer>;
  /** Wallet PDA */
  wallet: Address<TAccountWallet>;
  /** Vault PDA */
  vault: Address<TAccountVault>;
  /** Initial owner authority PDA */
  authority: Address<TAccountAuthority>;
  /** System Program */
  systemProgram?: Address<TAccountSystemProgram>;
  /** Rent Sysvar */
  rentSysvar?: Address<TAccountRentSysvar>;
  userSeed: CreateWalletInstructionDataArgs["userSeed"];
  authType: CreateWalletInstructionDataArgs["authType"];
  authPubkey: CreateWalletInstructionDataArgs["authPubkey"];
  credentialHash: CreateWalletInstructionDataArgs["credentialHash"];
  rpId: CreateWalletInstructionDataArgs["rpId"];
  authBump?: CreateWalletInstructionDataArgs["authBump"];
};

export function getCreateWalletInstruction<
  TAccountPayer extends string,
  TAccountWallet extends string,
  TAccountVault extends string,
  TAccountAuthority extends string,
  TAccountSystemProgram extends string,
  TAccountRentSysvar extends string,
  TProgramAddress extends Address = typeof LAZORKIT_PROGRAM_PROGRAM_ADDRESS,
>(
  input: CreateWalletInput<
    TAccountPayer,
    TAccountWallet,
    TAccountVault,
    TAccountAuthority,
    TAccountSystemProgram,
    TAccountRentSysvar
  >,
  config?: { programAddress?: TProgramAddress },
): CreateWalletInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountWallet,
  TAccountVault,
  TAccountAuthority,
  TAccountSystemProgram,
  TAccountRentSysvar
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? LAZORKIT_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    wallet: { value: input.wallet ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    rentSysvar: { value: input.rentSysvar ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.rentSysvar.value) {
    accounts.rentSysvar.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("wallet", accounts.wallet),
      getAccountMeta("vault", accounts.vault),
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("rentSysvar", accounts.rentSysvar),
    ],
    data: getCreateWalletInstructionDataEncoder().encode(
      args as CreateWalletInstructionDataArgs,
    ),
    programAddress,
  } as CreateWalletInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountWallet,
    TAccountVault,
    TAccountAuthority,
    TAccountSystemProgram,
    TAccountRentSysvar
  >);
}

export type ParsedCreateWalletInstruction<
  TProgram extends string = typeof LAZORKIT_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Payer and rent contributor */
    payer: TAccountMetas[0];
    /** Wallet PDA */
    wallet: TAccountMetas[1];
    /** Vault PDA */
    vault: TAccountMetas[2];
    /** Initial owner authority PDA */
    authority: TAccountMetas[3];
    /** System Program */
    systemProgram: TAccountMetas[4];
    /** Rent Sysvar */
    rentSysvar: TAccountMetas[5];
  };
  data: CreateWalletInstructionData;
};

export function parseCreateWalletInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCreateWalletInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 6,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      wallet: getNextAccount(),
      vault: getNextAccount(),
      authority: getNextAccount(),
      systemProgram: getNextAccount(),
      rentSysvar: getNextAccount(),
    },
    data: getCreateWalletInstructionDataDecoder().decode(instruction.data),
  };
}
