/**
 * AUTOGENERATED by Codama — instruction data encoders patched for program-v2 runtime layout.
 * Re-applied by scripts/patch-lazorkit-instructions.mjs after `pnpm generate:client`.
 */

import {
  combineCodec,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/kit/program-client-core";
import { LAZORKIT_PROGRAM_PROGRAM_ADDRESS } from "../programs";

export const EXECUTE_DEFERRED_DISCRIMINATOR = 7;

export function getExecuteDeferredDiscriminatorBytes(): ReadonlyUint8Array {
  return getU8Encoder().encode(EXECUTE_DEFERRED_DISCRIMINATOR);
}

export type ExecuteDeferredInstruction<
  TProgram extends string = typeof LAZORKIT_PROGRAM_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountWallet extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountDeferredExec extends string | AccountMeta<string> = string,
  TAccountRefundDestination extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountWallet extends string
        ? ReadonlyAccount<TAccountWallet>
        : TAccountWallet,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountDeferredExec extends string
        ? WritableAccount<TAccountDeferredExec>
        : TAccountDeferredExec,
      TAccountRefundDestination extends string
        ? WritableAccount<TAccountRefundDestination>
        : TAccountRefundDestination,
      ...TRemainingAccounts,
    ]
  >;

export type ExecuteDeferredInstructionData = {
  discriminator: number;
  instructions: ReadonlyUint8Array;
};

export type ExecuteDeferredInstructionDataArgs = {
  instructions: ReadonlyUint8Array;
};

export function getExecuteDeferredInstructionDataEncoder(): Encoder<ExecuteDeferredInstructionDataArgs> {
  return {
    getSizeFromValue: (value) => 1 + value.instructions.length,
    write(value, bytes, offset) {
      bytes.set(this.encode(value), offset);
    },
    encode(value) {
      const out = new Uint8Array(1 + value.instructions.length);
      out[0] = EXECUTE_DEFERRED_DISCRIMINATOR;
      out.set(value.instructions, 1);
      return out;
    },
  };
}

export function getExecuteDeferredInstructionDataDecoder(): Decoder<ExecuteDeferredInstructionData> {
  return {
    decode(bytes) {
      return {
        discriminator: bytes[0] ?? EXECUTE_DEFERRED_DISCRIMINATOR,
        instructions: bytes.slice(1),
      };
    },
  };
}

export function getExecuteDeferredInstructionDataCodec(): Codec<
  ExecuteDeferredInstructionDataArgs,
  ExecuteDeferredInstructionData
> {
  return combineCodec(
    getExecuteDeferredInstructionDataEncoder(),
    getExecuteDeferredInstructionDataDecoder(),
  );
}

export type ExecuteDeferredInput<
  TAccountPayer extends string = string,
  TAccountWallet extends string = string,
  TAccountVault extends string = string,
  TAccountDeferredExec extends string = string,
  TAccountRefundDestination extends string = string,
> = {
  /** Transaction payer */
  payer: TransactionSigner<TAccountPayer>;
  /** Wallet PDA */
  wallet: Address<TAccountWallet>;
  /** Vault PDA (signer for CPI) */
  vault: Address<TAccountVault>;
  /** DeferredExec PDA (read and closed) */
  deferredExec: Address<TAccountDeferredExec>;
  /** Account to receive rent refund from closed DeferredExec */
  refundDestination: Address<TAccountRefundDestination>;
  instructions: ExecuteDeferredInstructionDataArgs["instructions"];
};

export function getExecuteDeferredInstruction<
  TAccountPayer extends string,
  TAccountWallet extends string,
  TAccountVault extends string,
  TAccountDeferredExec extends string,
  TAccountRefundDestination extends string,
  TProgramAddress extends Address = typeof LAZORKIT_PROGRAM_PROGRAM_ADDRESS,
>(
  input: ExecuteDeferredInput<
    TAccountPayer,
    TAccountWallet,
    TAccountVault,
    TAccountDeferredExec,
    TAccountRefundDestination
  >,
  config?: { programAddress?: TProgramAddress },
): ExecuteDeferredInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountWallet,
  TAccountVault,
  TAccountDeferredExec,
  TAccountRefundDestination
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? LAZORKIT_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    wallet: { value: input.wallet ?? null, isWritable: false },
    vault: { value: input.vault ?? null, isWritable: true },
    deferredExec: { value: input.deferredExec ?? null, isWritable: true },
    refundDestination: {
      value: input.refundDestination ?? null,
      isWritable: true,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("wallet", accounts.wallet),
      getAccountMeta("vault", accounts.vault),
      getAccountMeta("deferredExec", accounts.deferredExec),
      getAccountMeta("refundDestination", accounts.refundDestination),
    ],
    data: getExecuteDeferredInstructionDataEncoder().encode(
      args as ExecuteDeferredInstructionDataArgs,
    ),
    programAddress,
  } as ExecuteDeferredInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountWallet,
    TAccountVault,
    TAccountDeferredExec,
    TAccountRefundDestination
  >);
}

export type ParsedExecuteDeferredInstruction<
  TProgram extends string = typeof LAZORKIT_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Transaction payer */
    payer: TAccountMetas[0];
    /** Wallet PDA */
    wallet: TAccountMetas[1];
    /** Vault PDA (signer for CPI) */
    vault: TAccountMetas[2];
    /** DeferredExec PDA (read and closed) */
    deferredExec: TAccountMetas[3];
    /** Account to receive rent refund from closed DeferredExec */
    refundDestination: TAccountMetas[4];
  };
  data: ExecuteDeferredInstructionData;
};

export function parseExecuteDeferredInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedExecuteDeferredInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 5,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      wallet: getNextAccount(),
      vault: getNextAccount(),
      deferredExec: getNextAccount(),
      refundDestination: getNextAccount(),
    },
    data: getExecuteDeferredInstructionDataDecoder().decode(instruction.data),
  };
}
