/**
 * Revibase brand stack — company first, products second.
 *
 * All user-facing UX strings live here. Import nested groups:
 * `copy.verify.holdToCheck`, `copy.wallet.*`, etc.
 */

export const brand = {
  company: "Revibase",
  companyLegal: "Revibase",
} as const;

export const products = {
  home: {
    name: "Wallets",
    tagline: "Your linked cards and accessories",
  },
} as const;

export const copy = {
  common: {
    tryAgain: "Try again",
    done: "Done",
    cancel: "Cancel",
    loading: "Loading…",
    back: "Back",
    close: "Close",
    wallet: "Wallet",
    remove: "Remove",
  },
  wallet: {
    copyAddress: "Copy address",
    addressCopied: "Address copied",
    addressCopyFailed: "Couldn’t copy address",
    openWalletAria: (label: string) => `Open wallet ${label}`,
    copyAddressAria: (label: string) => `Copy address ${label}`,
    addMoney: "Add money to get started",
    sendNeedsFunds: "Add money to send",
    balancesUpdating: "Updating…",
    balancesUpdateFailed: "Couldn’t update",
    manageDevice: "Manage device",
    send: "Send",
    receive: "Receive",
    activity: "Activity",
    tokens: "Tokens",
    collectibles: "Collectibles",
    seeAll: "See All",
    seeMore: "See more",
    searchTokens: "Search tokens",
    searchCollectibles: "Search collectibles",
    noMatchingTokens: "No tokens match",
    noMatchingCollectibles: "No collectibles match",
    noActivity: "No activity yet",
    settings: "Settings",
    settingsAria: "Open settings",
    signing: "Signing",
    rpcConnection: "RPC Connection",
    rpcBody:
      "Your wallet reads balances and collectibles through this Solana RPC. Use a DAS-capable provider (for example Helius) for full support.",
    rpcDefault: "Default",
    rpcCustom: "Custom",
    rpcCustomPrompt: "Enter your own RPC…",
    rpcCustomHint:
      "Paste an HTTPS RPC URL. API keys in the query string stay on this device and are hidden in the status banner.",
    rpcUrlLabel: "RPC URL",
    rpcSwitch: "Switch",
    rpcSwitchedDefault: "Using default RPC",
    rpcSwitchedCustom: "Using custom RPC",
    rpcBannerTitle: "Custom RPC",
    rpcBannerBody: (endpoint: string) => `Connected via ${endpoint}`,
    rpcBannerChange: "Change",
    rpcInvalidUrl: "Enter a valid http(s) RPC URL",
    advanced: "Advanced",
    backToCard: "Card",
    backToCardNamed: (name: string) => name,
    openWallet: "Wallet",
    openWalletAriaLabel: "Open wallet",
    holdToSend: "Hold to send",
    holdToReceive: "Hold to receive",
    holdToSave: "Hold to save",
    max: "Max",
    maxSolPerSend: "Max SOL per send",
    restoreDefault: "Restore Revibase",
    add: "Add",
    block: "Block",
    sent: "Sent",
    received: "Received",
    ofAvailableAsset: (available: string, symbol: string) =>
      `of ${available} ${symbol} available`,
    selectAsset: "Select asset",
    sendCollectible: "Sending 1 collectible",
    insufficientBalance: "Not enough balance for this amount",
    selfSend: "You can’t send to this wallet",
    viewReceipt: "View receipt",
    openCard: "Open card",
    feeBalance: "Network fees",
    feeBalanceHint: "Prepaid SOL Revibase uses to sponsor your sends",
    feeBalanceLow: "Fee balance is low. Top up before sending.",
    feeBalanceInsufficient:
      "Not enough fee balance to sponsor this transaction. Top up to continue.",
    topUpFees: "Top up fees",
    topUpFeesTitle: "Top up network fees",
    topUpFeesBody: "Send SOL from this wallet to preload sponsored fees.",
    topUpAmount: "Amount (SOL)",
    holdToTopUp: "Hold to top up",
    topUpPending: "Top-up sent. Balance updates in a moment.",
    topUpSuccess: "Top-up submitted",
    interfaceNft: "NFT",
    interfacePnft: "pNFT",
    interfaceCnft: "cNFT",
    interfaceCore: "Core",
    to: "To",
    from: "From",
    pasteAddress: "Paste address",
    invalidAddress: "Enter a valid address",
    tapAccessory: "Tap accessory",
    tapTheirAccessory: "Tap their accessory",
    accessoryLinked: "Accessory linked",
    clear: "Clear",
    shareAddress: "Share this address",
    share: "Share",
    copied: "Copied",
    receiveAnything: "Receive SOL, tokens, and collectibles to this wallet",
    receiveNearby: "Receive nearby",
    receiveNearbyHint: "Choose a token, then they tap to pay",
    refresh: "Refresh",
    refreshing: "Refreshing…",
    lastUpdated: (value: string) => `Updated ${value}`,
    contacts: "Contacts",
    saveContact: "Save contact",
    contactName: "Name",
    contactNote: "Note",
    noContacts: "No saved contacts yet",
    useContact: "Use contact",
    removeContact: "Remove",
    contactsHint: "Saved from sends on this phone.",
    firstRunTitle: "Your accessory wallet",
    firstRunBody:
      "Receive SOL or tokens here. Hold this item to your phone whenever you send.",
    firstRunCta: "Receive to get started",
    firstRunDismiss: "Skip for now",
    networkFeeSponsored: (amountUi: string) =>
      `Network fee ~${amountUi} SOL (sponsored)`,
    networkFeeShort: (amountUi: string) => `~${amountUi} SOL fee`,
    copySignature: "Copy signature",
    viewOnExplorer: "View on explorer",
    receiptPending: "Pending",
    receiptDetails: "Details",
    accessAndRecovery: "Access",
    accessAndRecoveryHint: "How this wallet stays yours",
    accessAndRecoveryBody:
      "Spending uses this physical item. This phone’s passkey signs you in and owns linked accessories. Approving exceptions or changing limits needs ownership on this phone. Revibase cannot restore access if you lose the item or this phone’s passkey. There is no seed phrase or backup.",
    recoveryAckTitle: "Keep this accessory safe",
    recoveryAckBody:
      "This wallet has no recovery phrase. If you lose the item or this phone’s passkey, the funds cannot be restored.",
    recoveryAckCta: "I understand",
    deviceLoginTitle: "Sign in to Revibase",
    deviceLoginBody:
      "Use this phone’s Face ID or passkey. Login if you’ve registered before; Register to create a new one.",
    deviceLoginCta: "Login",
    deviceRegisterCta: "Register",
    deviceLinkTitle: "Link this accessory",
    deviceLinkBody:
      "Link it to this phone so you can approve larger sends and change limits. You can skip and use the wallet as a visitor.",
    deviceLinkCta: "Link to this phone",
    deviceLinkSkip: "Not now",
    deviceVisitorNotice: "Visitor — linked on another phone",
    deviceVisitorUnlinkedNotice: "Visitor — not linked on this phone",
    deviceVisitorSoftDeny:
      "This send isn’t allowed by the owner’s limits. Ask them to approve it on their phone.",
    deviceAuthReady: "This phone is signed in",
    deviceAuthRemove: "Remove this phone",
    deviceAuthRemoved: "Phone removed",
    deviceUnlink: "Unlink this accessory",
    deviceUnlinked: "Accessory unlinked",
    deviceSignOut: "Sign out",
    deviceAddAccessory: "Hold to add",
    deviceAddAccessoryBody: "Hold a card or accessory to link or open it.",
    openApprovalContinue: "They can continue in the other app",
    nearbyPolicyTitle: "Send from their phone",
    nearbyPolicyBody:
      "This amount isn’t allowed by their spending settings. Ask them to open their wallet and send here instead.",
    nearbyPolicyFeeBody:
      "They don’t have enough fee balance to sponsor this. Ask them to top up on their phone, then send here.",
    nearbyPolicyGotIt: "Got it",
    signingBody:
      "Revibase signs with you when you tap and enforces your spending limits, recipients, and allowed actions. Change only if you trust another service.",
    signingCustomPolicyWarn:
      "A custom signing service ignores your Revibase policies. Spending limits, recipients, and allowed actions won’t apply until you restore Revibase.",
    signingCustomSaved:
      "Signing service updated. Revibase policies no longer apply.",
    signingRestored: "Restored Revibase signing",
    signingInvalidCustom:
      "Enter a valid verifier address and HTTPS endpoint",
    signingCurrent: "Current",
    signingDefault: "Revibase",
    useCustomSigning: "Use custom service…",
    customEndpoint: "Endpoint URL",
    customVerifier: "Verifier address",
    verifierPubkey: "Verifier pubkey",
    policyDefaultSigningOnly:
      "These settings apply only while Revibase is your signing service. A custom service ignores them.",
    approveSendTitle: "Approve this send?",
    approveSendBodyLimit: (limit: string) =>
      `This is over your $${limit} limit.`,
    approveSendBodyRecipient: "This address isn’t on your allowed list.",
    approveSendBodyTime: "Sending isn’t allowed right now.",
    approveOnce: "Approve once",
    changeLimits: "Change limits",
    sendBlockedHard:
      "This payment isn’t allowed by your settings. Change limits in Settings.",
    spendingLimits: "Spending limits",
    spendingLimitsHint: "You can still approve a larger send once.",
    maxPerSend: "Max per send",
    recipients: "Recipients",
    recipientsAnyone: "Anyone",
    recipientsAllowlist: "Allow list only",
    recipientsBlocked: "Blocked addresses",
    allowedActions: "Allowed actions",
    paymentsOnly: "Payments only",
    advancedPrograms: "Custom programs",
    programId: "Program ID",
    save: "Save",
    settingsSaved: "Settings saved",
  },
  home: {
    heading: "Wallets",
    emptyTitle: "No linked accessories",
    card: "Card",
    accessory: "Accessory",
    holdTitle: "Hold to open",
    holdBody: "Hold your item flat against the back of this phone.",
  },
  address: {
    default: "address",
    wallet: "wallet",
    linkedWallet: "linked wallet",
    mintAddress: "token ID",
    mintOwner: "owner wallet",
    cardId: "card ID",
    recipient: "recipient",
    walletAddress: "wallet address",
    copiedToClipboard: "Copied to clipboard",
    copyAria: (label: string, addr: string) => `Copy ${label} ${addr}`,
    copiedAria: (label: string) => `Copied ${label}`,
  },
  verify: {
    holdToCheck: "Hold to verify",
    introBody: "Hold your item flat against the back of this phone.",
    verifying: "Verifying…",
    verifyAgain: "Verify again",
    verifyAgainHint: "Hold here to re-check",
    verified: "Verified",
    verifiedAgainBody: "This item is authentic.",
    failed: "Couldn’t verify",
    failedBody:
      "Hold your item flat against the back of your phone and try again.",
    holdStill: "Hold still…",
    holdStillBody: "Keep your item against the phone until this finishes.",
    verifiedRecheckAria: "Verified. Verify again.",
    notVerified: "Not verified",
    notVerifiedHint: "Hold your item flat against the back of this phone.",
    verifyingChip: "Checking your item…",
    notSetUpTitle: "Not set up",
    notSetUpBody: "This item isn’t registered on Revibase yet.",
    loadTimedOut: "Taking too long",
    loadTimedOutBody: "Check your connection and try again.",
    verifyToUnlockShortcut: "Verify to unlock actions",
  },
  token: {
    verification: "Verification",
    linked: "Linked",
    notLinked: "Not linked",
    mintOwner: "Owner wallet",
    cardId: "Card ID",
    cardIdHint: "A unique ID for this physical card.",
    rarity: "Rarity",
    about: "About",
    attributes: "Attributes",
    details: "Details",
    collection: "Collection",
    showMore: "Show more",
    showLess: "Show less",
    showDetails: "Show details",
    hideDetails: "Hide details",
    mintAddress: "Token ID",
    itemLoadFailed: "Couldn’t load item",
    itemNotOnChain: "This item may no longer be available.",
    unnamedCard: "Collectible",
    wrongItem: "That isn’t this card or accessory.",
  },
  shortcut: {
    heading: "Shortcuts",
    openInBrowser: "Open in browser",
    embedBlocked: "This site can't be shown here.",
    loading: "Loading…",
  },
  gate: {
    openInBrowserTitle: "Open in your browser",
    openInBrowserBody: "Open this link in your phone’s browser to continue.",
    copyLink: "Copy link",
    openInSafari: "Open in Safari",
    linkCopied: "Link copied",
    linkCopyFailed: "Couldn’t copy link",
  },
} as const;

/** User-facing send / verify error titles and bodies (see user-errors.ts). */
export const errorCopy = {
  fallback: {
    title: "Not completed",
    body: "Something went wrong. Try again.",
  },
  couldntVerify: {
    title: "Couldn’t verify",
    body: "Hold your item here again and try once more.",
  },
  notEnoughMoney: {
    title: "Not enough money",
    body: "There isn’t enough in this wallet for this amount.",
  },
  paymentFailed: {
    title: "Not completed",
    body: "This couldn’t go through. Check the amount and try again.",
  },
  accessoryLocked: {
    title: "Accessory locked",
    body: "This accessory can’t send right now.",
  },
  sessionEnded: {
    title: "Verification timed out",
    body: "Hold your item here again to verify.",
  },
  accessoryNotReady: {
    title: "Accessory isn’t ready",
    body: "This accessory isn’t ready to send yet.",
  },
  wrongItem: {
    title: "Different item",
    body: "Hold the same item flat against the back of your phone.",
  },
  nfcVerifyFailed: {
    title: "Couldn’t verify",
    body: copy.verify.failedBody,
  },
  notSetUp: {
    title: copy.verify.notSetUpTitle,
    body: copy.verify.notSetUpBody,
  },
  itemNotFound: {
    title: "Item not found",
    body: "Hold your item here again to verify.",
  },
  enterAmount: {
    title: "Enter an amount",
    body: "Enter a valid amount.",
  },
  amountTooPrecise: {
    title: "Amount too precise",
    body: "Use fewer decimal places.",
  },
  tryAgainBody: {
    title: "Not completed",
    body: "Something went wrong. Try again.",
  },
} as const;
