/**
 * Revibase brand stack — company first, products second.
 *
 * All user-facing UX strings live here. Import nested groups:
 * `copy.verify.holdToCheck`, `copy.wallet.*`, etc.
 *
 * Voice: short labels, one-line bodies, plain words over jargon.
 * Titles name what the screen is; subtitles show current state.
 */

export const brand = {
  company: "Revibase",
  companyLegal: "Revibase",
} as const;

export const products = {
  home: {
    name: "Cards & Accessories",
    tagline: "Your cards and accessories",
  },
} as const;

export const copy = {
  common: {
    tryAgain: "Try again",
    done: "Done",
    cancel: "Cancel",
    loading: "Loading…",
    back: "Back",
    close: "Close",
    wallet: "Wallet",
    remove: "Remove",
    devnet: "Devnet",
  },
  wallet: {
    addressCopyFailed: "Couldn’t copy",
    showCardAria: "Back to card",
    addMoney: "Add money to get started",
    sendNeedsFunds: "Add money to send",
    balancesUpdating: "Updating…",
    balancesUpdateFailed: "Couldn’t update",
    manageDevice: "Settings",
    send: "Send",
    receive: "Receive",
    activity: "Activity",
    tokens: "Tokens",
    collectibles: "Collectibles",
    seeAll: "See all",
    seeMore: "See more",
    searchTokens: "Search tokens",
    searchCollectibles: "Search collectibles",
    noMatchingTokens: "No matches",
    noMatchingCollectibles: "No matches",
    noActivity: "No activity yet",
    settings: "Settings",
    /** Who cosigns sends (not authenticity verify). */
    signing: "Cosigner",
    rpcConnection: "Connection",
    rpcBody: "Where this wallet loads balances and collectibles from.",
    rpcDefault: "Default",
    rpcCustom: "Custom",
    rpcCustomPrompt: "Use your own URL…",
    rpcCustomHint: "Paste an HTTPS Solana RPC URL. Keys stay on this phone.",
    rpcUrlLabel: "URL",
    rpcSwitch: "Switch",
    rpcSwitchedDefault: "Using default connection",
    rpcSwitchedCustom: "Using custom connection",
    rpcBannerTitle: "Custom connection",
    rpcBannerBody: (endpoint: string) => `Via ${endpoint}`,
    rpcBannerChange: "Change",
    rpcInvalidUrl: "Enter a valid HTTPS URL",
    advanced: "Advanced",
    backToCard: "Card",
    backToCardChip: "Back",
    toWalletChip: "Wallet",
    openWalletAriaLabel: "Open wallet",
    holdToSend: "Hold to send",
    holdToReceive: "Hold to receive",
    holdToReceiveDesktopHint: "They’ll hold their item next",
    holdToSave: "Hold to save",
    save: "Save",
    holdToOpenTitle: "Hold to open",
    holdToOpenBody: "Hold this item flat against the back of this phone.",
    holdToOpenCta: "Hold to open",
    setupStepPasskey: "Step 1 of 2 · This phone",
    setupStepLink: "Step 2 of 2 · Link item",
    continueWithPasskey: "Continue with Face ID",
    setUpThisPhone: "Set up this phone",
    newPhoneHint: "New on this phone?",
    max: "Max",
    maxSolPerSend: "Max SOL per send",
    restoreDefault: "Use Revibase",
    add: "Add",
    sent: "Sent",
    received: "Received",
    ofAvailableAsset: (available: string, symbol: string) =>
      `${available} ${symbol} available`,
    selectAsset: "Choose asset",
    sendCollectible: "Sending 1 collectible",
    insufficientBalance: "Not enough balance",
    selfSend: "Can’t send to this wallet",
    cantReceiveFromSelf: "Can’t receive from this item",
    viewReceipt: "Receipt",
    openCard: "Open card",
    feeBalance: "Fee balance",
    feeBalanceHint: "Prepaid SOL used to cover network fees on your sends.",
    feeBalanceLow: "Fee balance is low. Top up before sending.",
    feeBalanceInsufficient: "Not enough fee balance. Top up to continue.",
    topUpFees: "Top up",
    topUpFeesTitle: "Top up fees",
    topUpFeesBody: "Move SOL from this wallet into your fee balance.",
    topUpAmount: "Amount (SOL)",
    holdToTopUp: "Hold to top up",
    topUpPending: "Top-up sent. Balance updates shortly.",
    topUpSuccess: "Top-up submitted",
    interfaceNft: "NFT",
    interfacePnft: "pNFT",
    interfaceCnft: "cNFT",
    interfaceCore: "Core",
    to: "To",
    from: "From",
    pasteAddress: "Paste address",
    invalidAddress: "Enter a valid address",
    tapAccessory: "Hold item",
    tapTheirAccessory: "Hold their item",
    accessoryLinked: "Linked",
    clear: "Clear",
    shareAddress: "Share address",
    share: "Share",
    copied: "Copied",
    receiveAnything: "Receive SOL, tokens, and collectibles here",
    receiveNearby: "Receive nearby",
    receiveNearbyHint: "Pick a token, then they hold to pay",
    refresh: "Refresh",
    refreshing: "Refreshing…",
    lastUpdated: (value: string) => `Updated ${value}`,
    contacts: "Contacts",
    saveContact: "Save contact",
    contactName: "Name",
    contactNote: "Note",
    noContacts: "No contacts yet",
    useContact: "Use",
    removeContact: "Remove",
    contactsHint: "Saved from sends on this phone.",
    firstRunTitle: "Get started",
    firstRunBody: "Receive money here. Hold this item to your phone when you send.",
    firstRunCta: "Receive",
    firstRunDismiss: "Not now",
    networkFeeSponsored: (amountUi: string) =>
      `Fee ~${amountUi} SOL (sponsored)`,
    networkFeeShort: (amountUi: string) => `~${amountUi} SOL fee`,
    copySignature: "Copy signature",
    viewOnExplorer: "View on explorer",
    receiptPending: "Pending",
    receiptDetails: "Receipt",
    receiptTime: "Time",
    accessAndRecovery: "This phone",
    accessAndRecoveryHint: "Link and recovery",
    accessAndRecoveryBody:
      "This item authorizes spends. Linking it to this phone lets you change limits and approve exceptions.",
    accessRecoveryRow: "Recovery address",
    recoveryWallet: "Recovery address",
    recoveryWalletBody:
      "Paste a Solana address you control. That wallet can move all funds from this item — without the item or Revibase — on the recover site.",
    recoveryWalletPubkey: "Address",
    recoveryWalletPubkeyPlaceholder: "Paste Solana address",
    recoveryWalletSave: "Hold to save",
    recoveryWalletReplace: "Hold to replace",
    recoveryWalletClear: "Clear address",
    recoveryWalletClearConfirmTitle: "Clear recovery address?",
    recoveryWalletClearConfirmBody:
      "That wallet can no longer recover funds here. You’ll need this item to set a new address.",
    recoveryWalletClearConfirmCta: "Clear",
    recoveryWalletSaved: "Recovery address saved",
    recoveryWalletCleared: "Recovery address cleared",
    recoveryWalletInvalid: "Enter a valid address",
    recoveryWalletSame: "Already set to this address",
    recoveryWalletConfigured: "Set",
    recoveryWalletNotConfigured: "Not set",
    recoveryWalletCurrent: "Current",
    recoveryWalletHint:
      "Public address only — never a private key or seed. Prefer a cold wallet.",
    recoveryWalletRecoverSiteNote:
      "Anyone with this key can empty the vault. Keep it offline and safe. Recover site coming soon.",
    recoveryWalletAck:
      "I understand this address can move all funds without this item.",
    recoveryAckTitle: "Add a recovery address?",
    recoveryAckBody:
      "If you lose this item, that address can restore funds. It can also move everything — choose a key you fully control.",
    recoveryAckCta: "Add address",
    recoveryAckSkip: "Not now",
    deviceLoginTitle: "Sign in",
    deviceLoginBody:
      "Manage linked items and spending limits with Face ID or your passkey.",
    homeSetupPasskeyBody:
      "Continue with Face ID, then hold this item to link it.",
    homeHaveItemHint: "Have an item? Hold it to your phone",
    homeLinkSetupTitle: "Hold to link",
    homeLinkSetupBody: "Hold this item flat against the phone to finish setup.",
    deviceLinkBody:
      "Link this item to change limits and approve larger sends on this phone.",
    deviceLinkCta: "Hold to link",
    deviceVisitorNotice: "Linked to another phone",
    deviceVisitorUnlinkedNotice: "This phone isn’t linked yet",
    deviceVisitorLinkAction: "Link",
    deviceVisitorSoftDeny:
      "Over the owner’s limits. Ask them to approve once on their linked phone.",
    deviceAuthReady: "Signed in on this phone",
    deviceSignOut: "Sign out",
    deviceUnlink: "Unlink this item",
    deviceUnlinkPolicyWarn:
      "Spending limits stay on. Soft denies may have no phone to approve them until you link again.",
    deviceUnlinked: "Item unlinked",
    deviceAddAccessory: "Hold to add",
    limitsSetupTitle: "Set up spending limits",
    limitsSetupBody:
      "Link this phone, then choose your caps. Limits apply with the Revibase cosigner.",
    limitsSetupCta: "Continue",
    limitsLinkedElsewhereTitle: "Linked to another phone",
    limitsLinkedElsewhereBody:
      "Unlink on that phone first, then come back here to set limits.",
    limitsStatusOff: "Not set",
    limitsStatusOn: "On",
    limitsStatusSetup: "Set up",
    limitsStatusInvalid: "Needs fix",
    limitsInvalidBody:
      "Saved limits are invalid. Save again to restore protection.",
    limitsTurnOff: "Turn off limits",
    limitsTurnedOff: "Limits off",
    openApprovalContinue: "They can continue in their app",
    openApprovalsTitle: "Needs your approval",
    openApprovalsLater: "Later",
    nearbyPolicyTitle: "Needs approval",
    nearbyPolicyBody:
      "Over their limits. Ask them to approve once on their linked phone, then try again.",
    nearbyPolicyFeeBody:
      "They need more fee balance. Ask them to top up, then try again.",
    nearbyPolicyGotIt: "Got it",
    signingBody:
      "Your item signs each send. Revibase joins the transaction and applies your limits.",
    signingCustomPolicyWarn:
      "A custom cosigner can move all funds on any tap. Revibase limits, recipients, and approvals will not apply.",
    signingCustomAck:
      "I understand this removes Revibase protection on every send.",
    signingCustomContinue: "Continue",
    signingCustomSaved: "Custom cosigner on — Revibase limits off",
    signingRestored: "Back to Revibase",
    signingInvalidCustom: "Enter a valid address and HTTPS URL",
    signingCurrent: "Current",
    signingDefault: "Revibase",
    signingCustom: "Custom",
    useCustomSigning: "Use custom cosigner…",
    customEndpoint: "Endpoint",
    customVerifier: "Cosigner address",
    verifierPubkey: "Cosigner address",
    setupDeviceNotLinked: "Not linked",
    setupDeviceLinkedElsewhere: "Linked elsewhere",
    setupDeviceLinkedHere: "Linked here",
    policyDefaultSigningOnly:
      "Off means sends are unrestricted with Revibase. Limits apply after you save.",
    policySection: "Limits",
    approveSendTitle: "Approve this send?",
    approveSendBodyLimit: (limit: string) => `Over your $${limit} limit.`,
    approveSendBodyRecipient: "Address isn’t on your allow list.",
    approveSendBodyRecipientDenied: "This address is on your block list.",
    approveSendBodyTime: "Sending isn’t allowed right now.",
    approveSendBodyApproval: "This send needs your one-time approval.",
    approveSendBodyInstruction:
      "This action isn’t allowed by your standing settings.",
    approveSendBodyProgram:
      "This program isn’t allowed by your standing settings.",
    approveSendBodyUnexpected:
      "This transaction couldn’t be checked against your settings.",
    approveSendAmount: "Amount",
    approveSendDestination: "To",
    approveSendMint: "Token",
    approveSendProgram: "Program",
    approveSendInstruction: "Action",
    approveOnce: "Approve once",
    changeLimits: "Change limits",
    sendBlockedHard:
      "This can’t be approved once — it would fail on-chain.",
    spendingLimits: "Spending limits",
    spendingLimitsHint:
      "Starting caps are 50 USDC and 0.1 SOL per send. You can approve a larger send once.",
    maxPerSend: "Max per send",
    recipients: "Recipients",
    recipientsHint: "Use wallet addresses. Token accounts are applied automatically.",
    recipientsAnyone: "Anyone",
    recipientsAllowlist: "Allow list",
    extraPrograms: "Extra programs",
    extraProgramsHint:
      "Programs this wallet can use without approving each send.",
    extraProgramsEmpty: "No extra programs yet",
    invalidProgramId: "Enter a valid program ID",
    programId: "Program ID",
    settingsSaved: "Saved",
  },
  home: {
    emptyTitle: "Add a card or accessory",
    emptyBody: "Hold it flat against the back of this phone.",
    cards: "Cards",
    accessories: "Accessories",
    card: "Card",
    accessory: "Accessory",
    holdTitle: "Hold to add",
    holdBody: "Hold flat against the back of this phone.",
  },
  address: {
    default: "address",
    wallet: "wallet",
    linkedWallet: "linked wallet",
    mintAddress: "token ID",
    mintOwner: "owner wallet",
    cardId: "card ID",
    recipient: "recipient",
    walletAddress: "wallet address",
    copiedToClipboard: "Copied",
    copyAria: (label: string, addr: string) => `Copy ${label} ${addr}`,
    copiedAria: (label: string) => `Copied ${label}`,
  },
  verify: {
    holdToCheck: "Hold to verify",
    introBody: "Hold flat against the back of this phone.",
    verifying: "Verifying…",
    verifyAgain: "Verify again",
    verifyAgainHint: "Hold to re-check",
    verifyCta: "Verify",
    verified: "Verified",
    verifiedAgainBody: "This item is authentic.",
    failed: "Couldn’t verify",
    failedBody: "Hold flat against the phone and try again.",
    holdStill: "Hold still…",
    holdStillBody: "Keep holding until this finishes.",
    verifiedRecheckAria: "Verified. Verify again.",
    notVerified: "Not verified",
    notVerifiedHint: "Hold flat against the back of this phone.",
    verifyingChip: "Checking…",
    notSetUpTitle: "Not set up",
    notSetUpBody: "This item isn’t on Revibase yet.",
    loadTimedOut: "Taking too long",
    loadTimedOutBody: "Check your connection and try again.",
    verifyToUnlockShortcut: "Verify to unlock",
  },
  token: {
    verification: "Authenticity",
    linked: "Linked",
    notLinked: "Not linked",
    mintOwner: "Owner",
    cardId: "Card ID",
    cardIdHint: "Unique ID for this card.",
    rarity: "Rarity",
    about: "About",
    attributes: "Attributes",
    details: "Details",
    collection: "Collection",
    showMore: "More",
    showLess: "Less",
    showDetails: "Details",
    hideDetails: "Hide",
    mintAddress: "Token ID",
    itemLoadFailed: "Couldn’t load",
    itemNotOnChain: "This item may no longer be available.",
    unnamedCard: "Collectible",
    wrongItem: "Wrong item.",
  },
  shortcut: {
    heading: "Shortcuts",
    openInBrowser: "Open in browser",
    embedBlocked: "Can’t show this site here.",
    loading: "Loading…",
  },
  gate: {
    openInBrowserTitle: "Open in browser",
    openInBrowserBody: "Open this link in your phone’s browser to continue.",
    copyLink: "Copy link",
    openInSafari: "Open in Safari",
    linkCopied: "Link copied",
    linkCopyFailed: "Couldn’t copy",
  },
} as const;

/** User-facing send / verify error titles and bodies (see user-errors.ts). */
export const errorCopy = {
  fallback: {
    title: "Not completed",
    body: "Something went wrong. Try again.",
  },
  couldntVerify: {
    title: "Couldn’t verify",
    body: "Hold here again and try once more.",
  },
  notEnoughMoney: {
    title: "Not enough",
    body: "This wallet doesn’t have enough for that amount.",
  },
  paymentFailed: {
    title: "Not completed",
    body: "Couldn’t go through. Check the amount and try again.",
  },
  accessoryLocked: {
    title: "Locked",
    body: "This item can’t send right now.",
  },
  sessionEnded: {
    title: "Timed out",
    body: "Hold here again to verify.",
  },
  accessoryNotReady: {
    title: "Not ready",
    body: "This item isn’t ready to send yet.",
  },
  wrongItem: {
    title: "Wrong item",
    body: "Hold the same item flat against your phone.",
  },
  nfcVerifyFailed: {
    title: "Couldn’t verify",
    body: copy.verify.failedBody,
  },
  notSetUp: {
    title: copy.verify.notSetUpTitle,
    body: copy.verify.notSetUpBody,
  },
  itemNotFound: {
    title: "Not found",
    body: "Hold here again to verify.",
  },
  enterAmount: {
    title: "Enter amount",
    body: "Enter a valid amount.",
  },
  amountTooPrecise: {
    title: "Too many decimals",
    body: "Use fewer decimal places.",
  },
  tryAgainBody: {
    title: "Not completed",
    body: "Something went wrong. Try again.",
  },
} as const;
