[package]
name = "phygital-payments"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "phygital_payments"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = [
    "anchor-lang/idl-build",
    "anchor-spl/idl-build",
    "phygital-token-client/anchor-idl-build",
]
anchor-debug = []
custom-heap = []
custom-panic = []

[dependencies]
anchor-lang = { version = "1.0.2", features = ["init-if-needed"] }
anchor-spl = "1.0.2"
phygital-token-client = { version = "0.9.0", features = ["anchor"] }
solana-sdk-ids = "3"
solana-sha256-hasher = "3"

[dev-dependencies]
anchor-lang = "1.0.2"
anchor-spl = "1.0.2"
base64 = "0.22.1"
borsh = "1"
litesvm = { version = "0.10.0", features = ["precompiles"] }
p256 = { version = "0.13.2", features = ["ecdsa"] }
phygital-token-client = { version = "0.9.0", features = ["anchor"] }
rand = "0.8"
sha2 = "0.10"
solana-account = "3"
solana-keypair = "3.0.1"
solana-message = "3.0.1"
solana-signer = "3.0.0"
solana-slot-hashes = "3"
solana-transaction = "3.0.2"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
